name: msb_store
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0
  firebase_auth: ^6.5.7
  flutter_native_splash: ^2.4.3
  lottie: ^3.1.0
  image_picker: ^1.2.3
  firebase_storage: ^13.4.6
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ඔබේ ලෝගෝ ඉමේජ් එක assets ෆෝල්ඩර් එකට දැමූ පසු මෙහි අංකනය කරන්න
  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo.png"
  
  # Android 12 වලදී අර සුදු box එක එන එක සම්පූර්ණයෙන්ම Disable කිරීමට
  android_12:
    color: "#FFFFFF"
    image: "assets/logo.png"
    # සමහර Android 12 ෆෝන් වල icon background එක වෙනස් කිරීමට මෙය උදව් වේ
    icon_background_color: "#FFFFFF"